### ISSUE TITLE
질문/답변에 대한 댓글 기능

### ISSUE THREAD

**Issue by malkoG** [cycorld/Unlock-n-ROR#23]

**Comment by cycorld** [comment]
모델을 두 개로 분리할지, 하나의 모델Comment 로 만들지 고민해봐야겠습니다.
개발이 쉬운건 두 개로 그냥 분리하는게 편할거구요

**Comment by malkoG** [comment]
Comment는 하나의 모델로 가는게 좋을 것 같습니다. 
물론 type이라는 필드를 별도로 만들어야 겠죠.
어차피 두 개의 모델로 분리할거면 차라리 boolean 타입(예를 들면, is_question)의 필드를 하나 만들어서 한꺼번에 다루는 것도 괜찮을 것 같습니다.

**Comment by cycorld** [comment]
참고 자료 : http://guides.rubyonrails.org/association_basics.html#polymorphic-associations

polymorphic-associations 으로 구현하면 좋겠습니다.

**Comment by steadymoka** [comment]
안녕하세요 R 팀의 이대명이라고 합니다.
궁금한게 있어서 남깁니다.

``` ruby
class CreateComments < ActiveRecord::Migration[5.0]
  def change
    create_table :comments do |t|
      t.string :content
      t.references :user, foreign_key: true
      t.references :commentable, polymorphic: true, index: true
      t.timestamps
    end
  end
end
```

이렇게 줬을때, 아래 사진과 같이 sqlitemanager 로 확인해보면 user_id 에 foreign_key 가 지정이 안되있는거 같은데, 위와 같이 하면 외래키가 제대로 설정 되는건지 궁급합니다

<img width="748" alt="2016-07-10 11 27 24" src="https://cloud.githubusercontent.com/assets/7301713/16711343/5e129490-4691-11e6-9492-70093129bea0.png">

**Comment by cycorld** [comment]
검색결과 아래 6 카운트 된 답변을 찾았습니다.
http://stackoverflow.com/questions/17956204/foreign-key-in-rails-4

레일즈 4.2 릴리즈노트를 보면 foreign key는 아직 mysql, mysql2, postgresql 어댑터만 지원한다고 하네요. sqlite는 리스트에 빠져 있습니다.
http://edgeguides.rubyonrails.org/4_2_release_notes.html#foreign-key-support

"The migration DSL now supports adding and removing foreign keys. They are dumped to schema.rb as well. At this time, only the mysql, mysql2 and postgresql adapters support foreign keys."

**Comment by steadymoka** [comment]
@cycorld 감사합니다 !! 개발환경 db를 바꿔야 겠네요 ..ㅎ

**Comment by cycorld** [comment]
@moka-a 개발하실 때 mysql 쓰시는 것도 좋긴하지만, 레일즈는 액티브레코드 덕에 FK를 직접 다룰 일이 없어 개발시엔 가볍게 sqlite으로 유지하는 것도 나쁘지 않은 듯합니다. mysql 쓰시면 rake db:drop 후에 rake db:create 명령어를 쓰거나 직접 mysql 콘솔에 들어가셔서 데이터베이스를 생성해주셔야 할거에요

**Comment by steadymoka** [comment]
@cycorld 아.. 넵 ! 답변감사합니다 !
